### ISSUE TITLE
Unable to claim games

### ISSUE THREAD

**Issue by chaoscreater** [davidjameshowell/epcigames-freegames-heroku#14]
Previously, I was using the cookies and it would claim games for me (but mostly fails). 

I saw that this Github project got updated, so I removed my fork and forked it again. I also removed all my Heroku instances and set up everything from scratch. This time, I'm not using the cookie and I'm just using my epic games username & password. I don't have MFA configured on my MFA account.

This is the log I get and I don't know what is wrong or how to troubleshoot it. Can someone point me in the right direction?

```
 Apr 15 12:08:04 epicgamesclaimeradminrl heroku/web.1 State changed from crashed to starting
Apr 15 12:08:08 epicgamesclaimeradminrl heroku/web.1 Starting process with command `docker-entrypoint.sh`
Apr 15 12:08:11 epicgamesclaimeradminrl app/web.1 Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
Apr 15 12:08:11 epicgamesclaimeradminrl app/web.1 Incoming env vars:
Apr 15 12:08:11 epicgamesclaimeradminrl app/web.1 RUN_ON_STARTUP: true
Apr 15 12:08:11 epicgamesclaimeradminrl app/web.1 CRON_SCHEDULE: 
Apr 15 12:08:11 epicgamesclaimeradminrl app/web.1 RUN_ONCE: true
Apr 15 12:08:11 epicgamesclaimeradminrl app/web.1 No JSON file found
Apr 15 12:08:11 epicgamesclaimeradminrl app/web.1 Setting config variables
Apr 15 12:08:11 epicgamesclaimeradminrl app/web.1 Run on startup: true
Apr 15 12:08:11 epicgamesclaimeradminrl app/web.1 Run once: true
Apr 15 12:08:11 epicgamesclaimeradminrl app/web.1 > epicgames-freegames-node@3.0.0 start /usr/app
Apr 15 12:08:11 epicgamesclaimeradminrl app/web.1 > node dist/src/index.js
Apr 15 12:08:12 epicgamesclaimeradminrl app/web.1 [2021-04-15 19:08:12.203 +0000] INFO  (18 on 742d48f1-cb33-447f-85e3-3acf925794e0): Checking free games for blah@gmail.com 
Apr 15 12:08:12 epicgamesclaimeradminrl app/web.1 [2021-04-15 19:08:12.236 +0000] ERROR (18 on 742d48f1-cb33-447f-85e3-3acf925794e0): Unexpected end of JSON input
Apr 15 12:08:12 epicgamesclaimeradminrl app/web.1     SyntaxError: Unexpected end of JSON input
Apr 15 12:08:12 epicgamesclaimeradminrl app/web.1         at JSON.parse (<anonymous>)
Apr 15 12:08:12 epicgamesclaimeradminrl app/web.1         at Object.newCookieJar (/usr/app/src/common/request.ts:49:29)
Apr 15 12:08:12 epicgamesclaimeradminrl app/web.1         at /usr/app/src/index.ts:16:29
Apr 15 12:08:12 epicgamesclaimeradminrl app/web.1         at async Promise.all (index 0)
Apr 15 12:08:12 epicgamesclaimeradminrl app/web.1         at main (/usr/app/src/index.ts:31:3)
Apr 15 12:08:12 epicgamesclaimeradminrl app/web.1 Exiting...
Apr 15 12:08:12 epicgamesclaimeradminrl app/web.1 Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
Apr 15 12:08:12 epicgamesclaimeradminrl app/web.1 OK
Apr 15 12:08:12 epicgamesclaimeradminrl heroku/web.1 Process exited with status 0
Apr 15 12:08:12 epicgamesclaimeradminrl heroku/web.1 State changed from starting to crashed
```

**Comment by davidjameshowell** [comment]
Hi @chaoscreater  - I just recently pushed an update (#15) which will resolve the above issue. The root cause was erroneously creating a blank config file, which was not intended to be created on first/initial runs.

**Comment by chaoscreater** [comment]
I've deleted my Heroku project and Github fork and set it up from scratch.

I'm still getting the same issue.

I'm not using any cookies this time.


![image](https://user-images.githubusercontent.com/18227319/119215786-fdb9e500-bb23-11eb-9210-07da8a7fb478.png)



```
2021-05-22T05:28:02.750969+00:00 app[web.1]:         at TLSSocket.SMTPConnection._onSocketData (/usr/app/node_modules/nodemailer/lib/smtp-connection/index.js:189:44)

2021-05-22T05:28:02.750969+00:00 app[web.1]:         at TLSSocket.emit (events.js:314:20)

2021-05-22T05:28:02.750969+00:00 app[web.1]:         at addChunk (_stream_readable.js:297:12)

2021-05-22T05:28:02.750970+00:00 app[web.1]:         at readableAddChunk (_stream_readable.js:272:9)

2021-05-22T05:28:02.750970+00:00 app[web.1]:         at TLSSocket.Readable.push (_stream_readable.js:213:10)

2021-05-22T05:28:02.775704+00:00 app[web.1]: Exiting...

2021-05-22T05:28:02.776495+00:00 app[web.1]: Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.

2021-05-22T05:28:02.785798+00:00 app[web.1]: OK

2021-05-22T05:28:02.831273+00:00 heroku[web.1]: Process exited with status 0

2021-05-22T05:28:02.934913+00:00 heroku[web.1]: State changed from up to crashed


```

**Comment by chaoscreater** [comment]
@davidjameshowell 

I've deleted my Heroku project and Github fork and set it up from scratch.

I'm still getting the same issue.

I'm not using any cookies this time.


![image](https://user-images.githubusercontent.com/18227319/119215786-fdb9e500-bb23-11eb-9210-07da8a7fb478.png)



```
2021-05-22T05:28:02.750969+00:00 app[web.1]:         at TLSSocket.SMTPConnection._onSocketData (/usr/app/node_modules/nodemailer/lib/smtp-connection/index.js:189:44)

2021-05-22T05:28:02.750969+00:00 app[web.1]:         at TLSSocket.emit (events.js:314:20)

2021-05-22T05:28:02.750969+00:00 app[web.1]:         at addChunk (_stream_readable.js:297:12)

2021-05-22T05:28:02.750970+00:00 app[web.1]:         at readableAddChunk (_stream_readable.js:272:9)

2021-05-22T05:28:02.750970+00:00 app[web.1]:         at TLSSocket.Readable.push (_stream_readable.js:213:10)

2021-05-22T05:28:02.775704+00:00 app[web.1]: Exiting...

2021-05-22T05:28:02.776495+00:00 app[web.1]: Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.

2021-05-22T05:28:02.785798+00:00 app[web.1]: OK

2021-05-22T05:28:02.831273+00:00 heroku[web.1]: Process exited with status 0

2021-05-22T05:28:02.934913+00:00 heroku[web.1]: State changed from up to crashed


```
