### ISSUE TITLE
Still unable to claim games with latest build

### ISSUE THREAD

**Issue by chaoscreater** [davidjameshowell/epcigames-freegames-heroku#16]
I've deleted my Heroku project and Github fork and set it up from scratch.

I'm still getting the same issue.

I'm not using any cookies this time.

![image](https://user-images.githubusercontent.com/18227319/119215786-fdb9e500-bb23-11eb-9210-07da8a7fb478.png)

```
2021-05-22T05:28:02.750969+00:00 app[web.1]:         at TLSSocket.SMTPConnection._onSocketData (/usr/app/node_modules/nodemailer/lib/smtp-connection/index.js:189:44)

2021-05-22T05:28:02.750969+00:00 app[web.1]:         at TLSSocket.emit (events.js:314:20)

2021-05-22T05:28:02.750969+00:00 app[web.1]:         at addChunk (_stream_readable.js:297:12)

2021-05-22T05:28:02.750970+00:00 app[web.1]:         at readableAddChunk (_stream_readable.js:272:9)

2021-05-22T05:28:02.750970+00:00 app[web.1]:         at TLSSocket.Readable.push (_stream_readable.js:213:10)

2021-05-22T05:28:02.775704+00:00 app[web.1]: Exiting...

2021-05-22T05:28:02.776495+00:00 app[web.1]: Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.

2021-05-22T05:28:02.785798+00:00 app[web.1]: OK

2021-05-22T05:28:02.831273+00:00 heroku[web.1]: Process exited with status 0

2021-05-22T05:28:02.934913+00:00 heroku[web.1]: State changed from up to crashed


```

**Comment by chaoscreater** [comment]
Can anyone help please?

**Comment by davidjameshowell** [comment]
@chaoscreater I just revisited this and I believe there was a fundamental flaw - you need to make sure that you are gathering the cookie from the `/id` endpoint as per [this instruction](https://github.com/claabs/epicgames-freegames-node#:~:text=While%20viewing%20the%20Epic%20Games%20Store%20page%2C%20open%20the%20EditThisCookie%20extension%20window%2C%20change%20the%20URL%20to%20https%3A//www.epicgames.com/id%2C%20and%20click%20the%20export%20button%3A)

I was able to export my cookie from `/id` and successfully use it to login without needing to solve any captchas.

**Comment by chaoscreater** [comment]
> 
> 
> @chaoscreater I just revisited this and I believe there was a fundamental flaw - you need to make sure that you are gathering the cookie from the `/id` endpoint as per [this instruction](https://github.com/claabs/epicgames-freegames-node#:~:text=While%20viewing%20the%20Epic%20Games%20Store%20page%2C%20open%20the%20EditThisCookie%20extension%20window%2C%20change%20the%20URL%20to%20https%3A//www.epicgames.com/id%2C%20and%20click%20the%20export%20button%3A)
> 
> I was able to export my cookie from `/id` and successfully use it to login without needing to solve any captchas.

I read in another thread that you do not need to use the cookies anymore, which should just use the username + password to login. This is what I'm using now (as per my screenshot). So do we still need cookies or not?

**Comment by davidjameshowell** [comment]
Yes, essentially cookies has been the only reliable method currently. I have since removed email/password from my config and have seen better results now. 

I'd advise that cookie is the current best and most reliable method as of writing.

**Comment by chaoscreater** [comment]
> 
> 
> Yes, essentially cookies has been the only reliable method currently. I have since removed email/password from my config and have seen better results now.
> 
> I'd advise that cookie is the current best and most reliable method as of writing.

Thanks, will try that.

I'm currently using another project to claim free games and their method is slightly different, maybe worth checking out as well:
https://github.com/xMistt/DeviceAuthGenerator
https://github.com/Revadike/epicgames-freebies-claimer

**Comment by PandH4cker** [comment]
Hi everyone,

It's about 1 week that I just set up the jobs and that EpicGamesFreeNodeRun is well scheduled to run every 5 hours (for myself).

But, it doesn't seem to claim the games on the Epic Games Store, I reseted my cookie and added another one but same, it does not claim on the Epic Games Store.

I have configured Mailgun as per of the README, but no mails about potential Captchas resolution.

On Heroku, I don't see activity about the scheduled job (deploy activity or whatever), does this is normal ?

I don't know what am I doing wrong, if someone could help ?

### EDIT: I Found that in Heroku logs:
```bash
2021-08-12T21:01:32.736148+00:00 app[web.1]:     user: "dray.raph@gmail.com"
2021-08-12T21:01:32.736149+00:00 app[web.1]:     availableGames: []
2021-08-12T21:01:32.736986+00:00 app[web.1]: [2021-08-12 21:01:32.736 +0000] INFO  (19 on a5634a43-efbe-4b6d-9888-e2481709ca46): Unpurchased free games
2021-08-12T21:01:32.736988+00:00 app[web.1]:     user: "dray.raph@gmail.com"
2021-08-12T21:01:32.736989+00:00 app[web.1]:     purchasableGames: []
2021-08-12T21:01:32.750500+00:00 app[web.1]: Exiting...
2021-08-12T21:01:32.751247+00:00 app[web.1]: Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
2021-08-12T21:01:32.754458+00:00 app[web.1]: OK
2021-08-12T21:01:32.827233+00:00 heroku[web.1]: Process exited with status 0
2021-08-12T21:01:32.984014+00:00 heroku[web.1]: State changed from up to crashed
```
It founds no free games but there are one new free game unclaimed.

### EDIT 2: Finally the application is crashing:
```bash
2021-08-12T21:18:45.224967+00:00 app[web.1]: [2021-08-12 21:18:45.191 +0000] INFO  (19 on 0c39abb0-4d3c-47d4-940e-ebdace236d43): Checking free games for dray.raph@gmail.com 
2021-08-12T21:18:47.483974+00:00 app[web.1]: [2021-08-12 21:18:47.482 +0000] INFO  (19 on 0c39abb0-4d3c-47d4-940e-ebdace236d43): Successfully refreshed login
2021-08-12T21:18:47.483985+00:00 app[web.1]:     user: "dray.raph@gmail.com"
2021-08-12T21:19:03.086365+00:00 app[web.1]: [2021-08-12 21:19:03.085 +0000] INFO  (19 on 0c39abb0-4d3c-47d4-940e-ebdace236d43): Available free games
2021-08-12T21:19:03.086375+00:00 app[web.1]:     user: "dray.raph@gmail.com"
2021-08-12T21:19:03.086375+00:00 app[web.1]:     availableGames: [
2021-08-12T21:19:03.086375+00:00 app[web.1]:       "Rebel Galaxy"
2021-08-12T21:19:03.086376+00:00 app[web.1]:     ]
2021-08-12T21:19:04.371019+00:00 app[web.1]: [2021-08-12 21:19:04.370 +0000] INFO  (19 on 0c39abb0-4d3c-47d4-940e-ebdace236d43): Unpurchased free games
2021-08-12T21:19:04.371030+00:00 app[web.1]:     user: "dray.raph@gmail.com"
2021-08-12T21:19:04.371030+00:00 app[web.1]:     purchasableGames: [
2021-08-12T21:19:04.371030+00:00 app[web.1]:       "Rebel Galaxy"
2021-08-12T21:19:04.371031+00:00 app[web.1]:     ]
2021-08-12T21:19:04.371645+00:00 app[web.1]: [2021-08-12 21:19:04.371 +0000] INFO  (19 on 0c39abb0-4d3c-47d4-940e-ebdace236d43): Purchasing Rebel Galaxy
2021-08-12T21:19:04.371645+00:00 app[web.1]:     user: "dray.raph@gmail.com"
2021-08-12T21:19:06.081230+00:00 app[web.1]: [2021-08-12 21:19:06.080 +0000] ERROR (19 on 0c39abb0-4d3c-47d4-940e-ebdace236d43): There was a problem processing your request.  Please try again later.
2021-08-12T21:19:06.081272+00:00 app[web.1]:     user: "dray.raph@gmail.com"
2021-08-12T21:19:06.116708+00:00 app[web.1]: [2021-08-12 21:19:06.082 +0000] ERROR (19 on 0c39abb0-4d3c-47d4-940e-ebdace236d43): Cannot read property 'map' of undefined
2021-08-12T21:19:06.116711+00:00 app[web.1]:     TypeError: Cannot read property 'map' of undefined
2021-08-12T21:19:06.116712+00:00 app[web.1]:         at Purchase.confirmOrder (/usr/app/src/purchase.ts:39:82)
2021-08-12T21:19:06.116713+00:00 app[web.1]:         at Purchase.purchase (/usr/app/src/purchase.ts:166:16)
2021-08-12T21:19:06.116713+00:00 app[web.1]:         at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-08-12T21:19:06.116714+00:00 app[web.1]:         at Purchase.purchaseGames (/usr/app/src/purchase.ts:174:7)
2021-08-12T21:19:06.116715+00:00 app[web.1]:         at /usr/app/src/index.ts:22:7
2021-08-12T21:19:06.116716+00:00 app[web.1]:         at async Promise.all (index 0)
2021-08-12T21:19:06.116716+00:00 app[web.1]:         at main (/usr/app/src/index.ts:31:3)
2021-08-12T21:19:06.165546+00:00 app[web.1]: Exiting...
2021-08-12T21:19:06.167559+00:00 app[web.1]: Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
2021-08-12T21:19:06.185028+00:00 app[web.1]: OK
2021-08-12T21:19:06.260457+00:00 heroku[web.1]: Process exited with status 0
2021-08-12T21:19:06.370005+00:00 heroku[web.1]: State changed from up to crashed
```
